// Script to clear attendance caches and test the fixes
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = process.env.VITE_SUPABASE_URL || 'https://cccxexvoahyeookqmxpl.supabase.co';
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjY3hleHZvYWh5ZW9va3FteHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjU5MDksImV4cCI6MjA2MzAwMTkwOX0.W4AhQt8-ZGkQa7i7rfsdJ5L1ZEn8Yx3crcrWCOGR9pA';

const supabase = createClient(supabaseUrl, supabaseKey);

async function clearAttendanceCache() {
  console.log('🧹 Clearing attendance cache...');
  
  try {
    // Check if there are any event_attendance records
    const { data: attendanceRecords, error: attendanceError } = await supabase
      .from('event_attendance')
      .select('*')
      .limit(5);

    if (attendanceError) throw attendanceError;

    console.log(`📊 Found ${attendanceRecords?.length || 0} attendance records`);

    if (attendanceRecords && attendanceRecords.length > 0) {
      console.log('\n📋 Sample attendance records:');
      attendanceRecords.forEach((record, index) => {
        console.log(`${index + 1}. Event ID: ${record.event_id}, Member ID: ${record.member_id}, Status: ${record.status}`);
      });
    }

    // Check if there are any events that might be causing the issue
    const { data: events, error: eventsError } = await supabase
      .from('events')
      .select('*')
      .limit(10);

    if (eventsError) throw eventsError;

    console.log(`\n📅 Found ${events?.length || 0} events`);

    if (events && events.length > 0) {
      console.log('\n📋 Sample events:');
      events.forEach((event, index) => {
        console.log(`${index + 1}. ID: ${event.id}, Title: ${event.title}, Date: ${event.start_date}, Org: ${event.organization_id || 'NULL'}`);
      });
    }

    // Check if there are any test or demo events
    const { data: testEvents, error: testError } = await supabase
      .from('events')
      .select('*')
      .or('title.ilike.%test%,title.ilike.%demo%,title.ilike.%sample%');

    if (testError) throw testError;

    console.log(`\n🧪 Found ${testEvents?.length || 0} test/demo events`);

    if (testEvents && testEvents.length > 0) {
      console.log('\n📋 Test/Demo events:');
      testEvents.forEach((event, index) => {
        console.log(`${index + 1}. ID: ${event.id}, Title: ${event.title}, Date: ${event.start_date}, Org: ${event.organization_id || 'NULL'}`);
      });
    }

    console.log('\n✅ Cache check completed. If you see duplicate events in the dashboard, they might be:');
    console.log('   1. Cached in the browser (try refreshing the page)');
    console.log('   2. Generated by frontend code (check for mock data)');
    console.log('   3. From a different organization or environment');

    return {
      attendanceRecords: attendanceRecords?.length || 0,
      events: events?.length || 0,
      testEvents: testEvents?.length || 0
    };

  } catch (error) {
    console.error('❌ Error checking cache:', error);
    throw error;
  }
}

// Run the check
clearAttendanceCache()
  .then((result) => {
    console.log('\n🎉 Cache check completed!');
    console.log('📈 Summary:', result);
    process.exit(0);
  })
  .catch((error) => {
    console.error('💥 Failed to check cache:', error);
    process.exit(1);
  }); 