-- Insert members data
INSERT INTO members (first_name, last_name, email, phone, address, role, status, notes, join_date)
VALUES
    ('JONATHAN', 'BAKER', NULL, NULL, jsonb_build_object('street', '169 EVENINGSTAR CT', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565-3616'), 'member', 'active', 'Additional member: LAURA BAKER', now()),
    ('LAURA', 'BAKER', NULL, NULL, jsonb_build_object('street', '169 EVENINGSTAR CT', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565-3616'), 'member', 'active', 'Additional member: JONATHAN BAKER', now()),
    ('CAROL', 'BALDWIN', 'cjbaldiwn@comcast.net', '925-516-8949', jsonb_build_object('street', '894 BLOSSOM DR', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513-6142'), 'member', 'active', NULL, now()),
    ('WENDY', 'BERMAN', NULL, '510-641-8056', jsonb_build_object('street', '146 REDOLDO DR', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('ROY', 'BLANCHARD', NULL, '925-234-1805', jsonb_build_object('street', 'PO BOX 592', 'city', 'BYRON', 'state', 'CA', 'zip', '94514'), 'member', 'active', 'Additional member: MILLIE BLANCHARD', now()),
    ('MILLIE', 'BLANCHARD', NULL, '925-234-1806', jsonb_build_object('street', 'PO BOX 592', 'city', 'BYRON', 'state', 'CA', 'zip', '94514'), 'member', 'active', 'Additional member: ROY BLANCHARD', now()),
    ('JOHN', 'BORSDORF', NULL, NULL, jsonb_build_object('street', '260 SPINDRIFT CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: KATHY BORSDORF', now()),
    ('KATHY', 'BORSDORF', NULL, NULL, jsonb_build_object('street', '260 SPINDRIFT CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: JOHN BORSDORF', now()),
    ('DAN', 'BURCH', NULL, NULL, jsonb_build_object('street', '260 SPINDRIFT CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: JANE BURCH', now()),
    ('JANE', 'BURCH', NULL, NULL, jsonb_build_object('street', '260 SPINDRIFT CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: DAN BURCH', now()),
    ('LESLIE', 'BUTLER', 'butlerleslie91@gmail.com', '925-206-8709', jsonb_build_object('street', '101 SHADY LN', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509'), 'member', 'active', NULL, now()),
    ('DEBORA', 'CHEW', NULL, NULL, jsonb_build_object('street', '330 SHADY OAK DRIVE', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', NULL, now()),
    ('CORAL', 'EGGERS', NULL, NULL, jsonb_build_object('street', '1546 MELLISSA CIRCLE', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509'), 'member', 'active', NULL, now()),
    ('DONALD', 'FRAASCH', NULL, '925-238-6849', jsonb_build_object('street', '4021 WOODHILL DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: ANNA FRAASCH', now()),
    ('ANNA', 'FRAASCH', NULL, NULL, jsonb_build_object('street', '4021 WOODHILL DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: DONALD FRAASCH', now()),
    ('ANGELA', 'GALLEGO', 'creationbyangela@gmail.com', '925-437-3245', jsonb_build_object('street', '321 LAVENDER WAY', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509'), 'member', 'active', NULL, now()),
    ('MARK', 'GARRO', NULL, NULL, jsonb_build_object('street', '1809 BLOSSOM DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94509-2823'), 'member', 'active', 'Additional member: VARAN GARRO', now()),
    ('VARAN', 'GARRO', NULL, NULL, jsonb_build_object('street', '1809 BLOSSOM DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94509-2823'), 'member', 'active', 'Additional member: MARK GARRO', now()),
    ('FELECIA', 'GAYE', NULL, NULL, jsonb_build_object('street', '2641 RANCHWOOD DR', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', NULL, now()),
    ('CESAR', 'GOMEZ', NULL, '408-646-9232', jsonb_build_object('street', '90 DE FREMERY DR', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', NULL, now()),
    ('MARILYN', 'GOULD', NULL, NULL, jsonb_build_object('street', '49 CAROL LN APT 213', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', NULL, now()),
    ('ANTHONY', 'GROSE', 'blbchurchpastor@gmail.com', '925-550-1617', jsonb_build_object('street', '1057 CLEAR LAKE DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: MARYJANE GROSE', now()),
    ('MARYJANE', 'GROSE', NULL, NULL, jsonb_build_object('street', '1057 CLEAR LAKE DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: ANTHONY GROSE', now()),
    ('JEANNE', 'HORGAN', NULL, NULL, jsonb_build_object('street', '4905 CHISM WAY', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94531'), 'member', 'active', NULL, now()),
    ('FOREST', 'HUEY', 'frhuey@gmail.com', '925-518-8439', jsonb_build_object('street', '510 CHRYSTY ST', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional email: hueyfr@aol.com', now()),
    ('DOROTHY', 'JONES', NULL, NULL, jsonb_build_object('street', '1708 MEDITERRANEO PL', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513-1767'), 'member', 'active', 'Additional member: JOSCELYN JONES', now()),
    ('JOSCELYN', 'JONES', NULL, NULL, jsonb_build_object('street', '1708 MEDITERRANEO PL', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513-1767'), 'member', 'active', 'Additional member: DOROTHY JONES', now()),
    ('MELVIN', 'JONES', NULL, NULL, jsonb_build_object('street', '278 EVELYN DR', 'city', 'PLEASANT HILL', 'state', 'CA', 'zip', '94523-2256'), 'member', 'active', NULL, now()),
    ('KATHY', 'KILLIPS', 'kskillips1121@gmail.com', '925-499-5136', jsonb_build_object('street', '2141CRESTVIEW LANE', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('ROSE', 'LEVYAS', NULL, '510-846-2824', jsonb_build_object('street', '1552 SPUMANTE LN', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', NULL, now()),
    ('KARIM', 'MAGUID', 'kmaguid@gmail.com', '925-813-9893', jsonb_build_object('street', '1363 SUNFLOWER LN', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', 'Additional member: AMBER MAGUID', now()),
    ('AMBER', 'MAGUID', 'ambermbesser@gmail.com', '925-813-9860', jsonb_build_object('street', '1363 SUNFLOWER LN', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', 'Additional member: KARIM MAGUID', now()),
    ('DIANNE', 'MELGOZA', NULL, NULL, jsonb_build_object('street', '441 ANNIL DR', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', NULL, now()),
    ('ERICA', 'MILLER', NULL, '925-856-7073', jsonb_build_object('street', '5321 FAIRSIDE WAY', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94531'), 'member', 'active', NULL, now()),
    ('DEBRA', 'MINAKER', 'debrad1202@yahoo.com', '925-783-1802', jsonb_build_object('street', '213 UPTON PYNE DR', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513-6425'), 'member', 'active', NULL, now()),
    ('MICHAEL', 'MURRAY', NULL, '925-783-6404', jsonb_build_object('street', '3020 HARRIS DR', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509-6344'), 'member', 'active', NULL, now()),
    ('YUKI', 'NAGASAWA', NULL, NULL, jsonb_build_object('street', '64 CANAL DR', 'city', 'BAYPOINT', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('RON', 'NARO', NULL, NULL, jsonb_build_object('street', '2904 BELLFLOWER CT', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509'), 'member', 'active', NULL, now()),
    ('DAVID', 'NAVARRETTE', 'totaleliteca@gmail.com', '925-813-1319', jsonb_build_object('street', '726 BEATRICE ST', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', NULL, now()),
    ('ELAYNE', 'NAVARRETTE', NULL, NULL, jsonb_build_object('street', 'PO BOX 660', 'city', 'COPPEROPOLIS', 'state', 'CA', 'zip', '95228-0668'), 'member', 'active', 'Additional member: JOE NAVARRETTE', now()),
    ('JOE', 'NAVARRETTE', NULL, NULL, jsonb_build_object('street', 'PO BOX 660', 'city', 'COPPEROPOLIS', 'state', 'CA', 'zip', '95228-0668'), 'member', 'active', 'Additional member: ELAYNE NAVARRETTE', now()),
    ('BERTHA', 'OCHOA', NULL, NULL, jsonb_build_object('street', '108 E TRIDENT', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('LORI', 'POWELL', NULL, '925-219-7534', jsonb_build_object('street', '101 SEENO ST', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('ROGER', 'POWELL', 'rdpowellags@comcast.net', '925-477-0725', jsonb_build_object('street', '3385 CONTRA LOMA BLVD APT 220A', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509'), 'member', 'active', NULL, now()),
    ('ANTONIO', 'SALDANA', NULL, NULL, jsonb_build_object('street', '47 PALM AV', 'city', 'PITTSBURG', 'state', 'CA', 'zip', '94565'), 'member', 'active', NULL, now()),
    ('DON', 'SCHULTE', NULL, NULL, jsonb_build_object('street', '502 H ST', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509-1266'), 'member', 'active', 'Additional member: CHERIL SCHULTE', now()),
    ('CHERIL', 'SCHULTE', NULL, NULL, jsonb_build_object('street', '502 H ST', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509-1266'), 'member', 'active', 'Additional member: DON SCHULTE', now()),
    ('ERIN', 'SPEDA', NULL, NULL, jsonb_build_object('street', '90 DE FREMERY DR', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', NULL, now()),
    ('FERMINA', 'SOUZA', NULL, NULL, jsonb_build_object('street', '4132 S. ROYAL LINKS CIRCLE', 'city', 'ANTIOCH', 'state', 'CA', 'zip', '94509-'), 'member', 'active', NULL, now()),
    ('OMERO', 'TALETPA', 'lor.tlatelpa@gmail.com', '925-418-9885', jsonb_build_object('street', '4574 FORD CT', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', 'Additional member: LORI TALETPA', now()),
    ('LORI', 'TALETPA', NULL, NULL, jsonb_build_object('street', '4574 FORD CT', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513'), 'member', 'active', 'Additional member: OMERO TALETPA', now()),
    ('REBECCA', 'TSUMA', NULL, NULL, jsonb_build_object('street', '20 DIANE CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: ROSE TSUMA', now()),
    ('ROSE', 'TSUMA', NULL, NULL, jsonb_build_object('street', '20 DIANE CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: REBECCA TSUMA', now()),
    ('CLIVE', 'TSUMA', 'cktsuma@gmail.com', '510-650-6462', jsonb_build_object('street', '20 DIANE CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: DOREEN KATIBA', now()),
    ('DOREEN', 'KATIBA', NULL, NULL, jsonb_build_object('street', '20 DIANE CT', 'city', 'OAKLEY', 'state', 'CA', 'zip', '94561'), 'member', 'active', 'Additional member: CLIVE TSUMA', now()),
    ('CAROL', 'VIRAMONTEZ', 'viramontezcarol@gmail.com', '925-813-1350', jsonb_build_object('street', '1038 BISMARCK TERRACE', 'city', 'BRENTWOOD', 'state', 'CA', 'zip', '94513-6918'), 'member', 'active', NULL, now())
ON CONFLICT (email) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    phone = EXCLUDED.phone,
    address = EXCLUDED.address,
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    notes = EXCLUDED.notes; 